apiVersion: v1
kind: Namespace
metadata:
  annotations:
    seriousben.com/repo: https://github.com/seriousben/seriousben.com
  labels:
    app.kubernetes.io/name: newsblur-to-hugo
    app.kubernetes.io/part-of: newsblur-to-hugo
    env: prod
  name: newsblur-to-hugo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    seriousben.com/repo: https://github.com/seriousben/seriousben.com
  labels:
    app: newsblur-to-hugo
    app.kubernetes.io/name: newsblur-to-hugo
    app.kubernetes.io/part-of: newsblur-to-hugo
    env: prod
  name: newsblur-to-hugo
  namespace: newsblur-to-hugo
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: newsblur-to-hugo
      app.kubernetes.io/name: newsblur-to-hugo
      app.kubernetes.io/part-of: newsblur-to-hugo
      env: prod
  template:
    metadata:
      annotations:
        seriousben.com/repo: https://github.com/seriousben/seriousben.com
      labels:
        app: newsblur-to-hugo
        app.kubernetes.io/name: newsblur-to-hugo
        app.kubernetes.io/part-of: newsblur-to-hugo
        env: prod
    spec:
      containers:
      - args:
        - poll
        env:
        - name: NEWSBLUR_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: newsblur
        - name: NEWSBLUR_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: newsblur
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: github
        image: seriousben/newsblur-to-hugo:32b7e92444b60a2bbb055f087584f6758f7a5de5
        name: worker
