apiVersion: v1
kind: Namespace
metadata:
  annotations:
    seriousben.com/repo: https://github.com/seriousben/seriousben.com
  labels:
    app.kubernetes.io/name: newsblur-to-hugo
    app.kubernetes.io/part-of: newsblur-to-hugo
    env: prod
  name: newsblur-to-hugo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    seriousben.com/repo: https://github.com/seriousben/seriousben.com
  labels:
    app: newsblur-to-hugo
    app.kubernetes.io/name: newsblur-to-hugo
    app.kubernetes.io/part-of: newsblur-to-hugo
    env: prod
  name: newsblur-to-hugo
  namespace: newsblur-to-hugo
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: newsblur-to-hugo
      app.kubernetes.io/name: newsblur-to-hugo
      app.kubernetes.io/part-of: newsblur-to-hugo
      env: prod
  template:
    metadata:
      annotations:
        seriousben.com/repo: https://github.com/seriousben/seriousben.com
      labels:
        app: newsblur-to-hugo
        app.kubernetes.io/name: newsblur-to-hugo
        app.kubernetes.io/part-of: newsblur-to-hugo
        env: prod
    spec:
      containers:
      - image: seriousben/newsblur-to-hugo:latest
        name: worker
