---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: continuous-deployment
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch", "extensions", "update", "patch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: continuous-deployment
subjects:
- kind: User
  name: newsblur-to-hugo-deployer@projects-seriousben.iam.gserviceaccount.com 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: continuous-deployment
  apiGroup: rbac.authorization.k8s.io
---
