name: pullrequest
on: [pull_request]

env:
  IMAGE: seriousben/newsblur-to-hugo

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        # uses docker://reviewdog/action-golangci-lint:v1 # pre-build docker image
        with:
          github_token: ${{ secrets.github_token }}

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker build
        run: |
          docker build -t "$IMAGE":"$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .

  kubectl-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Ensure manifest generation
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: 3.2.1
          command: |
            kustomize build deploy/overlay > build-kustomized-overlay.yaml
            diff -u build-kustomized-overlay.yaml deploy/manifests/kustomized-overlay.yaml
